pipeline {
  agent any
  environment {
    DOCKER_IMAGE = "myorg/hr-helper:${env.BUILD_NUMBER}"
    DB_CREDS = credentials('postgres-db-credentials')
    REDIS_URL = 'redis://redis:6379/0'
    RABBITMQ_URL = 'amqp://guest:guest@rabbitmq:5672/'
  }
  stages {
    stage('Lint & Test') {
      steps {
        script {
          sh 'docker build -t test-image -f docker/Dockerfile .'
          sh 'docker run --rm test-image pytest --maxfail=1 --disable-warnings'
          sh 'docker run --rm test-image flake8 .'
        }
      }
    }
    stage('Build Docker') {
      steps {
        sh 'docker build -t $DOCKER_IMAGE -f docker/Dockerfile .'
      }
    }
    stage('Migrate DB') {
      steps {
        sh 'alembic upgrade head'
      }
    }
    stage('Push Image') {
      steps {
        sh 'docker push $DOCKER_IMAGE'
      }
    }
    stage('Deploy') {
      steps {
        sh 'docker-compose -f docker/docker-compose.yml up -d'
      }
    }
  }
  post {
    always {
      archiveArtifacts artifacts: '**/logs/*.log', allowEmptyArchive: true
    }
  }
} 